// Generated by Wrangler by running `wrangler types`

interface Env {
	REPLICATE_API_TOKEN: string;
	OPENAI_API_KEY: string;
	CARTOON_IMAGE_BUCKET: string;
	CartoonBucket: R2Bucket;
	DB: D1Database;
}
